READ UpgradeDB\Ver1060303\Entity.sql;

IF EXISTS(SELECT 1 FROM sys.sysprocedure where proc_name = 'UpdateLoginRecIP') THEN
   DROP PROCEDURE UpdateLoginRecIP
END IF;

CREATE PROCEDURE DBA.UpdateLoginRecIP(
in In_UserId char(20),
in In_IPAddress char(20),
out Out_LoginSGSPGenId char(30))
begin
  declare TS_LogoutTimeStamp timestamp;
  set TS_LogoutTimeStamp=Now(*);
  update LoginRec set
    LoginRec.ModuleLogoutTime = TS_LogoutTimeStamp where
    LoginRec.UserId = In_UserId and
    LoginRec.IPAddress = In_IPAddress and
    LoginRec.ModuleLogoutTime is null;
  commit work;
  select Max(LoginSGSPGenId) into Out_LoginSGSPGenId from LoginRec where
    UserId = In_UserId and
    ModuleLogoutTime = TS_LogoutTimeStamp and
    IPAddress = In_IPAddress
end
;

delete from DBA.Task;
delete from DBA.RemDetailsTmpl;
delete from DBA.RemSetup;
delete from DBA.RemFunction;

/* Insert Into RemFunction Table */
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('EmpeeCessation','Core',0,'VsBTaskReminder','Employee - Cessation Date','Employee', 'CessationDate','Employee E', '','','','','','','E.EmployeeSysID','','','','','EmployeeName','EmployeeID','CessationDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('EmpeeConfirmationDue','Core',0,'VsBTaskReminder','Employee - Confirmation Due','Employee', 'DATEADD(DAY,-1,ConfirmationDate)','Employee E', '','','','','','','E.EmployeeSysID','','','','','EmployeeName','EmployeeID','DATEADD(DAY,-1,ConfirmationDate)','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('EmpeeHire','Core',0,'VsBTaskReminder','Employee - Hire Date','Employee', 'HireDate','Employee E', '','','','','','','E.EmployeeSysID','','','','','EmployeeName','EmployeeID','HireDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('EmpeeRetirementDue','Core',0,'VsBTaskReminder','Employee - Retirement Due','Employee', 'DATEADD(DAY,-1,RetirementDate)','Employee E', '','','','','','','E.EmployeeSysID','','','','','EmployeeName','EmployeeID','DATEADD(DAY,-1,RetirementDate)','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRNextAppraisal','HR',0,'VsBTaskReminder','HR - Appraisal - Next Appraisal Date','Appraisal', 'AppraisalNext','Appraisal A JOIN Personal P ON A.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','AppraisalSysId','','','','PersonalName','IdentityNo','AppraisalNext','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRAwardDiscFollowup','HR',0,'VsBTaskReminder','HR - Award/Discipline - Follow-up Date','AwardDisc', 'FollowUpDate','AwardDisc A JOIN Personal P ON A.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','AwardDiscSysId','','','','PersonalName','IdentityNo','FollowUpDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRBondEnd','HR',0,'VsBTaskReminder','HR - Bond - End Date','Bond', 'EndDate','Bond B JOIN Personal P ON B.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','BondSysId','','','','PersonalName','IdentityNo','EndDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRCourseStart','HR',0,'VsBTaskReminder','HR - Course Schedule - Start Date','CourseSchedule', 'CourseStartDate','CourseSchedule C', '','','','','','','CourseCode','CourseScheduleSysId','','','','CourseCode','CourseStartDate','','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRItemIssuedExpiry','HR',0,'VsBTaskReminder','HR - Item Issued - Expiry Date','ItemAssignItem', 'ExpiryDate','ItemAssignItem I JOIN Personal P ON I.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','ItemAssignItemSysId','','','','PersonalName','IdentityNo','ExpiryDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRItemNextIssue','HR',0,'VsBTaskReminder','HR - Item Issued - Next Issue Date','ItemAssignItem', 'NextIssueDate','ItemAssignItem I JOIN Personal P ON I.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','ItemAssignItemSysId','','','','PersonalName','IdentityNo','NextIssueDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRMedExamFollowup','HR',0,'VsBTaskReminder','HR - Medical Examination - Follow-up Date','MedExRec', 'FollowUpDate','MedExRec M JOIN Personal P ON M.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','MedExRecSysId','','','','PersonalName','IdentityNo','FollowUpDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRMembershipExpiry','HR',0,'VsBTaskReminder','HR - Membership - Expiry Date ','Memship', 'MemExpiryDate','Memship M JOIN Personal P ON M.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','MemSysId','','','','PersonalName','IdentityNo','MemExpiryDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRInterview','HR',0,'VsBTaskReminder','HR - Recruitment - Interview Date','InterviewSchedule', 'InterviewDate','InterviewSchedule S JOIN (Applicant A JOIN Personal P ON A.PersonalSysID=P.PersonalSysID)', '','','','','','','P.PersonalSysID','InterviewSchSysId','','','','PersonalName','IdentityNo','InterviewDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRSkillExpiry','HR',0,'VsBTaskReminder','HR - Skill - Expire on','SkillLevel', 'SkillExpiryDate','SkillLevel S JOIN Personal P ON S.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','S.SkillCode','S.SkillEffectiveDate','','','PersonalName','IdentityNo','SkillExpiryDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRTest','HR',0,'VsBTaskReminder','HR - Test Evaluation - Test Date','HRTest', 'HRTestDate','HRTest H JOIN Personal P ON H.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','H.HRTestSysId','','','','PersonalName','IdentityNo','HRTestDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('HRTrainingCertExpiry','HR',0,'VsBTaskReminder','HR - Training - Certificate Expiry Date','Training', 'CertificateExpiryDate','Training T JOIN Personal P ON T.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','T.TrainingSysId','','','','PersonalName','IdentityNo','CertificateExpiryDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('LvHoliday','Leave',0,'VsBTaskReminder','Leave - Calendar - Holiday Date','Holidays', 'HolidayStartDate','Holidays H', '','','','','','','CountryID','HolidayID','HolidayStartDate','','','CountryID','HolidayID','HolidayStartDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('LvCreditLeaveExpiry','Leave',0,'VsBTaskReminder','Leave - Credit Leave - Expire Date','AdjustCredit', 'CreditExpireDate','AdjustCredit A JOIN Employee E ON A.EmployeeSysID=E.EmployeeSysID', '','','','','','','E.EmployeeSysID','LeaveTypeId','AdjEffectiveDate','AdjType','','EmployeeName','EmployeeID','CreditExpireDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('LvLeaveApplication','Leave',0,'VsBTaskReminder','Leave - Leave Application - From Date','LeaveApplication', 'LveAppFromDate','LeaveApplication L JOIN Employee E ON L.EmployeeSysID=E.EmployeeSysID', '','','','','','','E.EmployeeSysID','LeaveAppSGSPGenId','','','','EmployeeName','EmployeeID','LveAppFromDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('PayNextIncrement','Core',0,'VsBTaskReminder','Pay - Basic Rate Progression - Next Increment Date','BasicRateProgression', 'BRProgNextIncDate','BasicRateProgression B JOIN Employee E ON B.EmployeeSysID=E.EmployeeSysID', '','','','','','','E.EmployeeSysID','BRProgDate','','','','EmployeeName','EmployeeID','BRProgNextIncDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('PayContractEnd','Core',0,'VsBTaskReminder','Pay - Contract Progression - End Date','ContractProgression', 'ContractEndDate','ContractProgression C JOIN Employee E ON C.EmployeeSysID=E.EmployeeSysID', '','','','','','','E.EmployeeSysID','ContractStartDate','','','','EmployeeName','EmployeeID','ContractEndDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('PayEPExpiry','Pay',0,'VsBTaskReminder','Pay - EP Progression - Expiry Date','EmployPassProgression', 'EPExiryDate','EmployPassProgression EP JOIN Employee E ON EP.EmployeeSysID=E.EmployeeSysID', '','','','','','','E.EmployeeSysID','EPEffectiveDate','','','','EmployeeName','EmployeeID','EPExiryDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('PayFWLExpiry','Pay',0,'VsBTaskReminder','Pay - FWL Progression - Expiry Date','FWLProgression', 'FWLExpiryDate','FWLProgression F JOIN Employee E ON F.EmployeeSysID=E.EmployeeSysID', '','','','','','','E.EmployeeSysID','FWLEffectiveDate','','','','EmployeeName','EmployeeID','FWLExpiryDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('PersonBirthday','Core',0,'VsBTaskReminder','Personnel - Date of Birth','Personal', 'DateOfBirth','Personal P', '','','','','','','P.PersonalSysID','','','','','PersonalName','EmployeeID','DateOfBirth','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('PersonResStatusEff','Core',0,'VsBTaskReminder','Personnel - Residence Status Effective Date','ResidenceStatusRecord', 'ResStatusEffectiveDate','ResidenceStatusRecord R JOIN Personal P ON R.PersonalSysID=P.PersonalSysID', '','','','','','','P.PersonalSysID','ResStatusEffectiveDate','','','','PersonalName','EmployeeID','ResStatusEffectiveDate','','');
Insert Into DBA.RemFunction(RemFunctionID,TaskCategoryID,IsCustomised,DllName,FuncMessage,SysDateTableID,SysDateAttributeID,SysDateSqlJoin,SysDateSqlCond,ParamNameU1,ParamNameU2,ParamNameU3,ParamNameU4,ParamNameU5,FuncKeyAttributeId1,FuncKeyAttributeId2,FuncKeyAttributeId3,FuncKeyAttributeId4,FuncKeyAttributeId5,FuncKeyword1,FuncKeyword2,FuncKeyword3,FuncKeyword4,FuncKeyword5) Values ('SystemUserExpiry','Core',0,'VsBTaskReminder','System User - Expiry Date','SystemUser', 'ExpiryDate','SystemUser S', '','','','','','','UserID','','','','','UserID','ExpiryDate','','','');

/* Insert Into RemDetailsTmpl Table */
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('EmpeeCessation',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('EmpeeConfirmationDue',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('EmpeeHire',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('EmpeeRetirementDue',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRNextAppraisal',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRAwardDiscFollowup',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRBondEnd',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRCourseStart',1,'Course (<K1>) start on <K2>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRItemIssuedExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRItemNextIssue',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRMedExamFollowup',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRMembershipExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRInterview',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRSkillExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRTest',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('HRTrainingCertExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('LvHoliday',1,'<K1> (<K2>), falls on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('LvCreditLeaveExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('LvLeaveApplication',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('PayNextIncrement',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('PayContractEnd',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('PayEPExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('PayFWLExpiry',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('PersonBirthday',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('PersonResStatusEff',1,'<K1> (<K2>), due on <K3>');
Insert Into DBA.RemDetailsTmpl(RemFunctionID,RemDetailsTmplOrder,Details) Values ('SystemUserExpiry',1,'User (<K1>), expire on <K2>');

commit work;