/* System Attribute  */

If Not Exists(Select SYSTABLEID from SystemAttribute where SYSTABLEID='PolicyRecord' and SYSATTRIBUTEID='Ana_BPJSKesehatanWage') Then
 Insert into SystemAttribute(SYSTABLEID,SYSATTRIBUTEID,SYSUSERDEFINEDNAME,SYSSPECIALATTRIBUTE,SYSPARAMETER1,SYSPARAMETER2,SYSPARAMETER3,SYSPARAMETER4,SYSPARAMETER5)
 Values('PolicyRecord','Ana_BPJSKesehatanWage','BPJS Kes Wage',1,'','','','','');
End if;

If Not Exists(Select SYSTABLEID from SystemAttribute where SYSTABLEID='PolicyRecord' and SYSATTRIBUTEID='Ana_TotalEmpeeBPJSKesehatan') Then
 Insert into SystemAttribute(SYSTABLEID,SYSATTRIBUTEID,SYSUSERDEFINEDNAME,SYSSPECIALATTRIBUTE,SYSPARAMETER1,SYSPARAMETER2,SYSPARAMETER3,SYSPARAMETER4,SYSPARAMETER5)
 Values('PolicyRecord','Ana_TotalEmpeeBPJSKesehatan','Total Employee BPJS Kes',1,'','','','','');
End if;

If Not Exists(Select SYSTABLEID from SystemAttribute where SYSTABLEID='PolicyRecord' and SYSATTRIBUTEID='Ana_TotalEmperBPJSKesehatan') Then
 Insert into SystemAttribute(SYSTABLEID,SYSATTRIBUTEID,SYSUSERDEFINEDNAME,SYSSPECIALATTRIBUTE,SYSPARAMETER1,SYSPARAMETER2,SYSPARAMETER3,SYSPARAMETER4,SYSPARAMETER5)
 Values('PolicyRecord','Ana_TotalEmperBPJSKesehatan','Total EmpER BPJS Kes',1,'','','','','');
End if;


/* AnItem Lookup  */

If Not Exists(Select ANLYSLOOKUPID from AnItemLookup where ANLYSLOOKUPID='BPJSKesehatanWage') Then
 Insert into AnItemLookup(ANLYSLOOKUPID,SYSTABLEID,SYSATTRIBUTEID,ANLYSITEMTYPEID,ANLYSMAPFIELD,ANLYSTABLE,ANLYSFUNCTION,ANLYSCONDITION,ANLYSMAPFIELDPREV,ANLYSMAPFIELDVAR)
 Values('BPJSKesehatanWage','PolicyRecord','Ana_BPJSKesehatanWage','PaySystem','AnlysAmount1','PolicyRecord','sum(CurrEEManWage)','','AnlysFAmount1','AnlysDoubleValue1');
End if;

If Not Exists(Select ANLYSLOOKUPID from AnItemLookup where ANLYSLOOKUPID='TotalEmpeeBPJSKesehatan') Then
Insert into AnItemLookup(ANLYSLOOKUPID,SYSTABLEID,SYSATTRIBUTEID,ANLYSITEMTYPEID,ANLYSMAPFIELD,ANLYSTABLE,ANLYSFUNCTION,ANLYSCONDITION,ANLYSMAPFIELDPREV,ANLYSMAPFIELDVAR)
Values('TotalEmpeeBPJSKesehatan','PolicyRecord','Ana_TotalEmpeeBPJSKesehatan','PaySystem','AnlysAmount1','PolicyRecord','sum(CurrEEManContri)','','AnlysFAmount1','AnlysDoubleValue1');
End if;

If Not Exists(Select ANLYSLOOKUPID from AnItemLookup where ANLYSLOOKUPID='TotalEmperBPJSKesehatan') Then
Insert into AnItemLookup(ANLYSLOOKUPID,SYSTABLEID,SYSATTRIBUTEID,ANLYSITEMTYPEID,ANLYSMAPFIELD,ANLYSTABLE,ANLYSFUNCTION,ANLYSCONDITION,ANLYSMAPFIELDPREV,ANLYSMAPFIELDVAR)
Values('TotalEmperBPJSKesehatan','PolicyRecord','Ana_TotalEmperBPJSKesehatan','PaySystem','AnlysAmount1','PolicyRecord','sum(CurrERManContri)','','AnlysFAmount1','AnlysDoubleValue1');
End if;

/* ANLYSDISPSECTION  */

Delete from anlysitemrecord;
Delete from ANLYSDISPSECTION;

If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_1') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_1','CalTotalWage','SysIStat_1',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_2') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_2','AllocatedMVC','SysIStat_1',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_3') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_3','AllocatedNWC','SysIStat_1',3);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_4') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_4','CalOTAmount','SysIStat_1',4);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_5') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_5','CalOTBackPay','SysIStat_1',5);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_6') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_6','CalShiftAmount','SysIStat_1',6);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_7') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_7','CalLveDeductAmt','SysIStat_1',7);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_8') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_8','CalBackPay','SysIStat_1',8);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_9') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_9','AllowanceAmount','SysIStat_2',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_10') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_10','AllowanceKeywordUserDefinedName','SysIStat_2',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_11') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_11','CalTotalGrossWage','SysIStat_3',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_12') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_12','JamsostekWage','SysIStat_3',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_13') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_13','BPJSKesehatanWage','SysIStat_3',3);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_14') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_14','TaxGrossWage','SysIStat_3',4);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_15') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_15','TotalEmpeeJamsostek','SysIStat_3',5);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_16') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_16','TotalEmpeeBPJSKesehatan','SysIStat_3',6);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_17') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_17','TotalTaxAmt','SysIStat_3',7);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_18') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_18','CalNetWage','SysIStat_3',8);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_19') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_19','TotalEmperPaymentOldAge','SysIStat_3',9);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_20') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_20','TotalEmperPaymentAccident','SysIStat_3',10);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_21') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_21','TotalEmplyerPaymentDeath','SysIStat_3',11);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_22') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_22','TotalEmperBPJSKesehatan','SysIStat_3',12);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_23') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_23','NPLDaysTaken','SysIStat_3',13);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_24') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_24','NPLHours','SysIStat_3',14);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_25') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_25','AbsDaysTaken','SysIStat_3',15);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_26') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_26','LateHours','SysIStat_3',16);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_27') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_27','SumOTFreq','SysIStat_4',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_28') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_28','ShiftFrequency','SysIStat_5',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_29') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_29','AnlCurrLvePeriodTaken','SysIStat_6',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_30') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_30','SickCurrLvePeriodTaken','SysIStat_6',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_31') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_31','PayHeadCount','SysIStat_6',3);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_32') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_32','FreeNumeric1','SysIStat_3',17);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_33') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_33','FreeNumeric2','SysIStat_3',18);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_34') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_34','FreeNumeric3','SysIStat_3',19);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_35') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_35','FreeNumeric4','SysIStat_3',20);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDStat_36') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDStat_36','FreeNumeric5','SysIStat_3',21);
End if;

If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_1') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_1','AllocatedBasicRate','SysIVar_1',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_2') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_2','AllocatedMVC','SysIVar_1',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_3') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_3','AllocatedNWC','SysIVar_1',3);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_4') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_4','CalTotalWage','SysIVar_1',4);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_5') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_5','CalOTAmount','SysIVar_1',5);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_6') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_6','CalOTBackPay','SysIVar_1',6);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_7') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_7','CalShiftAmount','SysIVar_1',7);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_8') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_8','CalLveDeductAmt','SysIVar_1',8);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_9') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_9','CalBackPay','SysIVar_1',9);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_10') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_10','FAllowanceAmount','SysIVar_2',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_11') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_11','FDeductionAmount','SysIVar_3',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_12') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_12','FReimbursementAmount','SysIVar_4',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_13') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_13','CalTotalGrossWage','SysIVar_5',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_14') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_14','CalGrossWage','SysIVar_5',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_15') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_15','JamsostekWage','SysIVar_5',3);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_16') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_16','BPJSKesehatanWage','SysIVar_5',4);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_17') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_17','TaxGrossWage','SysIVar_5',5);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_18') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_18','TotalEmpeeJamsostek','SysIVar_5',6);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_19') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_19','TotalEmpeeBPJSKesehatan','SysIVar_5',7);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_20') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_20','TotalTaxAmt','SysIVar_5',8);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_21') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_21','CalNetWage','SysIVar_5',9);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_22') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_22','TotalEmperPaymentOldAge','SysIVar_5',10);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_23') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_23','TotalEmperPaymentAccident','SysIVar_5',11);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_24') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_24','TotalEmplyerPaymentDeath','SysIVar_5',12);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_25') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_25','TotalEmperBPJSKesehatan','SysIVar_5',13);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_26') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_26','NPLDaysTaken','SysIVar_5',14);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_27') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_27','NPLHours','SysIVar_5',15);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_28') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_28','AbsDaysTaken','SysIVar_5',16);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_29') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_29','LateHours','SysIVar_5',17);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_30') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_30','SumOTFreq','SysIVar_6',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_31') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_31','ShiftFrequency','SysIVar_7',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_32') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_32','AnlCurrLvePeriodTaken','SysIVar_8',1);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_33') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_33','SickCurrLvePeriodTaken','SysIVar_8',2);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_34') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_34','FreeNumeric1','SysIVar_5',18);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_35') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_35','FreeNumeric2','SysIVar_5',19);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_36') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_36','FreeNumeric3','SysIVar_5',20);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_37') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_37','FreeNumeric4','SysIVar_5',21);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_38') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_38','FreeNumeric5','SysIVar_5',22);
End if;
If not exists(select ANLYSDISPLAYSYSID from ANLYSDISPSECTION where ANLYSDISPLAYSYSID='SysDVar_39') Then
 Insert Into ANLYSDISPSECTION(ANLYSDISPLAYSYSID,ANLYSLOOKUPID,ANLYSITEMSYSID,DISPLAYSUBSECTION)
 Values('SysDVar_39','PayHeadCount','SysIVar_8',3);
End if;

/* Laser payslip Default Data */

If Not Exists(select * from SYSTEMRPTCOMP where SYSRPTID='Payslip - Laser' and SYSRPTCOMPNAME='JamsoBPJS_CheckBox') Then
Insert Into SYSTEMRPTCOMP(SYSRPTID,SYSRPTCOMPNAME,SYSRPTCOMPDESC,SYSRPTCOMPTYPE,ISRPTKEY,RPTKEYINDEX)
Values('Payslip - Laser','JamsoBPJS_CheckBox','Jamostek / BPJS Kes','int',0,NULL);
End if;

If Not Exists(select * from RptCompConfig where RPTCOMPSYSID='Sys_78') Then
Insert Into RptCompConfig(RPTCOMPSYSID,RPTCONFIGID,SYSRPTID,SYSRPTCOMPNAME)
Values('Sys_78','_Payslip - Laser','Payslip - Laser','JamsoBPJS_CheckBox');
End if;

If Not Exists(select * from RptCompItemConfig where RPTCOMPSYSID='Sys_78') Then
Insert Into RptCompItemConfig(RPTCOMPSYSID,RPTCOMPITEMSYSID,ITEMVALUE)
Values('Sys_78','1','0');
End if;

commit work;