Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Confirmation Letter','Company','Company','Company Info','Company');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Confirmation Letter','ConfirmedEmp','ConfirmedEmp','Confirmed Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Confirmation Letter','PersonalQuery','Personal','Personal Table','Personal');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Confirmation Letter','EmployeeQuery','Employee','Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Acceptance of Resign','Company','Company','Company Info','Company');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Acceptance of Resign','ResignedEmp','ResignedEmp','Resigned Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Acceptance of Resign','EmployeeQuery','Employee','Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Increment Letter','Company','Company','Company Info','Company');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Increment Letter','IncrementEmp','IncrementEmp','Increment Employee','BasicRateProgression');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Increment Letter','BasicRateProgression','BasicRateProgression','Basic Rate Progression','BasicRateProgression');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Increment Letter','IncrementEmp','Employee','Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Letter of Promotion','Company','Company','Company Info','Company');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Letter of Promotion','PromotedEmp','PromotedEmp','Promoted Employee','CareerProgression');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Letter of Promotion','PromotedEmp','Employee','Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Letter of Promotion','BasicRateProgression','BasicRateProgression','Basic Rate Progression','BasicRateProgression');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Employment Letter','Company','Company','Company Info','Company');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Employment Letter','EmploymentEmp','EmploymentEmp','Offer of Employment Employee','Employee');
Insert Into DBA.CustomTable (QueryFolderID, CustomQueryID, CustomTableID, TableDesc, PhysicalName) Values ('Employment Letter','EmployeeQuery','Employee','Employee','Employee');