if not exists(select * from ModuleScreenGroup where ModuleScreenId = 'PayLabMarketSurvey') then
  insert into ModuleScreenGroup(ModuleScreenId,Mod_ModuleScreenId,ModuleScreenName,MainModuleName,HideOnlyWage,HideScreenForWage,IsEPClassic,EC_ModuleScreenId)
  values('PayLabMarketSurvey','PayReports','Labour Market Survey','Pay',0,0,0,'');
end if;

if not exists (select ModuleScreenId from ModuleScreenGroup where ModuleScreenId='CorePDPARpt' ) Then
   insert ModuleScreenGroup(ModuleScreenId,Mod_ModuleScreenId,ModuleScreenName,MainModuleName,HideOnlyWage,HideScreenForWage,IsEPClassic,EC_ModuleScreenId) 
   values ('CorePDPARpt','CoreReports','Personal Information Consent Form','Core',0,0,0,NULL);
end if;


/*Labour Market Survey Usage Item */

if not exists (select UsageItemId from UsageItem where UsageItemId='LabourMktSurveyCount' ) Then
   insert UsageItem(UsageItemID,UsagegrpID,ItemDesc,ItemKey1Desc,ItemKey2Desc,ItemKey3Desc,FieldLoc,Query,QueryCond) 
   values ('LabourMktSurveyCount','StatSubmit','Labour Market Survey','PreviewSurvey_Button','','','IntegerValue',
   'SELECT ItemRefKey1 AS Key1, ItemRefKey2 AS Key2, ItemRefKey3 AS Key3, ModifyDateTime AS ModDateTime, IntegerValue AS RetValue FROM UsageItemRecord ',
   'WHERE UsageItemID=''LabourMktSurveyCount'' AND IntegerValue>0;');
end if;



/* Insert Formula Property for System Leave Encashment*/
if not exists(select * from FormulaProperty where FormulaId='Sys_ANLEncashment' AND KeywordId='SubjAdditional') then
 Insert into FormulaProperty (FormulaId,KeywordId) Values('Sys_ANLEncashment','SubjAdditional');
end if;

if not exists(select * from FormulaProperty where FormulaId='Sys_ANLEncashment' AND KeywordId='SubjSDF') then
 Insert into FormulaProperty (FormulaId,KeywordId) Values('Sys_ANLEncashment','SubjSDF');
end if;


/*Labour Market Survey Setup */

delete from LabSurveySetup;

Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('1','(a) Total number of paid employees as at [DStartDate-1]','Local','ManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('2','(a) Total number of paid employees as at [DStartDate-1]','Local','AssManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('3','(a) Total number of paid employees as at [DStartDate-1]','Local','ClericalSaleService','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('4','(a) Total number of paid employees as at [DStartDate-1]','Local','Production','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('5','(a) Total number of paid employees as at [DStartDate-1]','PR','ManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('6','(a) Total number of paid employees as at [DStartDate-1]','PR','AssManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('7','(a) Total number of paid employees as at [DStartDate-1]','PR','ClericalSaleService','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('8','(a) Total number of paid employees as at [DStartDate-1]','PR','Production','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('9','(a) Total number of paid employees as at [DStartDate-1]','Foreigners','ManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,3,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('10','(a) Total number of paid employees as at [DStartDate-1]','Foreigners','AssManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,3,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('11','(a) Total number of paid employees as at [DStartDate-1]','Foreigners','ClericalSaleService','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,3,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('12','(a) Total number of paid employees as at [DStartDate-1]','Foreigners','Production','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate])',1,3,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('13','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','LocalPR','ManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('14','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','LocalPR','AssManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('15','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','LocalPR','ClericalSaleService','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('16','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','LocalPR','Production','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('17','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','Foreigners','ManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('18','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','Foreigners','AssManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('19','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','Foreigners','ClericalSaleService','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('20','(b) Number of new employees who joined your establishment during [DStartDate] to [DEndDate]','Foreigners','Production','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(hiredate >= [QStartDate] and hiredate <= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc) and employee.personalsysid not in (select personalsysid from employee as emp where emp.personalsysid = employee.personalsysid and (cessationdate = ''1899-12-30'' or cessationdate >= [QStartDate]) and (hiredate < [QStartDate]))',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('21','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','LocalPR','ManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('22','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','LocalPR','AssManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('23','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','LocalPR','ClericalSaleService','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('24','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','LocalPR','Production','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('25','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','Foreigners','ManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('26','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','Foreigners','AssManagerProf','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('27','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','Foreigners','ClericalSaleService','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('28','(c) Total number of employees who left your establishment during [DStartDate] to [DEndDate]','Foreigners','Production','','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('29','(ci) Resignations','LocalPR','ManagerProf','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('30','(ci) Resignations','LocalPR','AssManagerProf','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('31','(ci) Resignations','LocalPR','ClericalSaleService','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('32','(ci) Resignations','LocalPR','Production','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('33','(ci) Resignations','Foreigners','ManagerProf','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('34','(ci) Resignations','Foreigners','AssManagerProf','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('35','(ci) Resignations','Foreigners','ClericalSaleService','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('36','(ci) Resignations','Foreigners','Production','Resignations','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('37','(cii) Expiry of contracts','LocalPR','ManagerProf','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('38','(cii) Expiry of contracts','LocalPR','AssManagerProf','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('39','(cii) Expiry of contracts','LocalPR','ClericalSaleService','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('40','(cii) Expiry of contracts','LocalPR','Production','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('41','(cii) Expiry of contracts','Foreigners','ManagerProf','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('42','(cii) Expiry of contracts','Foreigners','AssManagerProf','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('43','(cii) Expiry of contracts','Foreigners','ClericalSaleService','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('44','(cii) Expiry of contracts','Foreigners','Production','ExpiryOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('45','(ciii) Retirements','LocalPR','ManagerProf','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('46','(ciii) Retirements','LocalPR','AssManagerProf','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('47','(ciii) Retirements','LocalPR','ClericalSaleService','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('48','(ciii) Retirements','LocalPR','Production','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('49','(ciii) Retirements','Foreigners','ManagerProf','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('50','(ciii) Retirements','Foreigners','AssManagerProf','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('51','(ciii) Retirements','Foreigners','ClericalSaleService','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('52','(ciii) Retirements','Foreigners','Production','Retirements','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('53','(civ) Retrenchments','Local','ManagerProf','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('54','(civ) Retrenchments','Local','AssManagerProf','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('55','(civ) Retrenchments','Local','ClericalSaleService','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('56','(civ) Retrenchments','Local','Production','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('57','(civ) Retrenchments','PR','ManagerProf','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('58','(civ) Retrenchments','PR','AssManagerProf','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('59','(civ) Retrenchments','PR','ClericalSaleService','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('60','(civ) Retrenchments','PR','Production','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('61','(civ) Retrenchments','Foreigners','ManagerProf','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('62','(civ) Retrenchments','Foreigners','AssManagerProf','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('63','(civ) Retrenchments','Foreigners','ClericalSaleService','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('64','(civ) Retrenchments','Foreigners','Production','Retrenchments','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('65','(cv) Early release of contract','Local','ManagerProf','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('66','(cv) Early release of contract','Local','AssManagerProf','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('67','(cv) Early release of contract','Local','ClericalSaleService','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('68','(cv) Early release of contract','Local','Production','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('69','(cv) Early release of contract','PR','ManagerProf','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('70','(cv) Early release of contract','PR','AssManagerProf','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('71','(cv) Early release of contract','PR','ClericalSaleService','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('72','(cv) Early release of contract','PR','Production','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,2,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('73','(cv) Early release of contract','Foreigners','ManagerProf','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('74','(cv) Early release of contract','Foreigners','AssManagerProf','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('75','(cv) Early release of contract','Foreigners','ClericalSaleService','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('76','(cv) Early release of contract','Foreigners','Production','EarlyRelOfContracts','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('77','(cvi) Dismissals','LocalPR','ManagerProf','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('78','(cvi) Dismissals','LocalPR','AssManagerProf','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('79','(cvi) Dismissals','LocalPR','ClericalSaleService','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('80','(cvi) Dismissals','LocalPR','Production','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('81','(cvi) Dismissals','Foreigners','ManagerProf','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('82','(cvi) Dismissals','Foreigners','AssManagerProf','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('83','(cvi) Dismissals','Foreigners','ClericalSaleService','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('84','(cvi) Dismissals','Foreigners','Production','Dismissals','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('85','(cvii) Transfer to subsidiaries/associate establishments','LocalPR','ManagerProf','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('86','(cvii) Transfer to subsidiaries/associate establishments','LocalPR','AssManagerProf','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('87','(cvii) Transfer to subsidiaries/associate establishments','LocalPR','ClericalSaleService','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('88','(cvii) Transfer to subsidiaries/associate establishments','LocalPR','Production','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('89','(cvii) Transfer to subsidiaries/associate establishments','Foreigners','ManagerProf','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('90','(cvii) Transfer to subsidiaries/associate establishments','Foreigners','AssManagerProf','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('91','(cvii) Transfer to subsidiaries/associate establishments','Foreigners','ClericalSaleService','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('92','(cvii) Transfer to subsidiaries/associate establishments','Foreigners','Production','TransferToSubsidiary','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('93','(cviii) Others','LocalPR','ManagerProf','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('94','(cviii) Others','LocalPR','AssManagerProf','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('95','(cviii) Others','LocalPR','ClericalSaleService','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('96','(cviii) Others','LocalPR','Production','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,1,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('97','(cviii) Others','Foreigners','ManagerProf','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('98','(cviii) Others','Foreigners','AssManagerProf','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('99','(cviii) Others','Foreigners','ClericalSaleService','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,3,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('100','(cviii) Others','Foreigners','Production','Others','select employee.PersonalSysId, employee.employeesysid from employee join personal','(cessationdate >= [QStartDate] and cessationdate<= [QEndDate]) and employee.employeesysid in (select first employeesysid from employee as em where em.PersonalSysId = employee.personalSysId order by em.hiredate desc)',1,3,4,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('101','(d) Total number of paid employees as at [DEndDate]','Local','ManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,1,1,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('102','(d) Total number of paid employees as at [DEndDate]','Local','AssManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,1,2,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('103','(d) Total number of paid employees as at [DEndDate]','Local','ClericalSaleService','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,1,3,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('104','(d) Total number of paid employees as at [DEndDate]','Local','Production','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,1,4,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('105','(d) Total number of paid employees as at [DEndDate]','PR','ManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,2,1,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('106','(d) Total number of paid employees as at [DEndDate]','PR','AssManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,2,2,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('107','(d) Total number of paid employees as at [DEndDate]','PR','ClericalSaleService','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,2,3,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('108','(d) Total number of paid employees as at [DEndDate]','PR','Production','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,2,4,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('109','(d) Total number of paid employees as at [DEndDate]','Foreigners','ManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,3,1,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('110','(d) Total number of paid employees as at [DEndDate]','Foreigners','AssManagerProf','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,3,2,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('111','(d) Total number of paid employees as at [DEndDate]','Foreigners','ClericalSaleService','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,3,3,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('112','(d) Total number of paid employees as at [DEndDate]','Foreigners','Production','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',1,3,4,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('113','(a) Total number of paid employees as of [DEndDate]','FullTime','','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',2,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('114','(a) Total number of paid employees as of [DEndDate]','PartTime','','','select EmployeeSysId from employee','(cessationdate = ''1899-12-30'' or cessationdate > [QEndDate]) and (hiredate < [QEndDate])',2,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('115','(b) Total weekly standard hours of work for a normal week in [DEndYearMonth] (hours)','FullTime','Hours','','select EEHoursperDay*AveWorkDaysPerWeek as WorkingHours,employee.employeesysid as EmployeeSysId from employee join payemployee join empeewkcalen on payemployee.employeesysid = empeewkcalen.employeesysid join Calendar on empeewkcalen.CalendarId = Calendar.CalendarId','(cessationdate = ''1899-12-30'' or cessationdate >= [QFirstDayOfEndMonth]) and (hiredate <= [QFirstDayOfEndMonth])',2,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('116','(b) Total weekly standard hours of work for a normal week in [DEndYearMonth] (hours)','PartTime','Hours','','select EEHoursperDay*AveWorkDaysPerWeek as WorkingHours,employee.employeesysid as EmployeeSysId from employee join payemployee join empeewkcalen on payemployee.employeesysid = empeewkcalen.employeesysid join Calendar on empeewkcalen.CalendarId = Calendar.CalendarId','(cessationdate = ''1899-12-30'' or cessationdate >= [QFirstDayOfEndMonth]) and (hiredate <= [QFirstDayOfEndMonth])',2,1,2,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('117','(c) Total number of employees who were paid for overtime worked in [DEndYearMonth]','FullTime','','','select distinct OTRecord.employeesysid as employeesysid from OTRecord join payemployee join employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QFirstDayOfEndMonth]) and (hiredate <= [QFirstDayOfEndMonth]) and (FGetPhyYearGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndYear] and FGetPhyMonthGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndMonth]) and (OTType != ''OTFixedRate'' and CurrentOTFreq <>0)',2,1,1,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('118','(c) Total number of employees who were paid for overtime worked in [DEndYearMonth]','PartTime','','','select distinct OTRecord.employeesysid as employeesysid from OTRecord join payemployee join employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QFirstDayOfEndMonth]) and (hiredate <= [QFirstDayOfEndMonth]) and (FGetPhyYearGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndYear] and FGetPhyMonthGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndMonth]) and (OTType != ''OTFixedRate'' and CurrentOTFreq <>0)',2,1,2,0);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('119','(d) Total paid overtime hours worked in [DEndYearMonth] (hours)','FullTime','Hours','','select EmployeeSysId, sum(WorkingHours) as WorkingHours from (select OTRecord.employeesysid as employeesysid,(case OTType when ''OTHourRate'' then CurrentOTFreq when ''OTDayRate'' then CurrentOTFreq*(select EEHoursperDay from payemployee join empeewkcalen on payemployee.employeesysid = empeewkcalen.employeesysid where payemployee.employeesysid=OTRecord.EmployeeSysid) else 0 end)as WorkingHours from OTRecord join payemployee join employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QFirstDayOfEndMonth]) and (hiredate <= [QFirstDayOfEndMonth]) and (FGetPhyYearGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndYear] and FGetPhyMonthGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndMonth]) and (OTType != ''OTFixedRate'' and CurrentOTFreq <>0)) as temp group by employeesysid',2,1,1,1);
Insert into LabSurveySetup(LabSurveySetupId,Description,Rule1,Rule2,Rule3,Query,QueryCondition,DisplaySection,DisplayRow,DisplayColumn,ShowEmpDetail) Values('120','(d) Total paid overtime hours worked in [DEndYearMonth] (hours)','PartTime','Hours','','select EmployeeSysId, sum(WorkingHours) as WorkingHours from (select OTRecord.employeesysid as employeesysid,(case OTType when ''OTHourRate'' then CurrentOTFreq when ''OTDayRate'' then CurrentOTFreq*(select EEHoursperDay from payemployee join empeewkcalen on payemployee.employeesysid = empeewkcalen.employeesysid where payemployee.employeesysid=OTRecord.EmployeeSysid) else 0 end)as WorkingHours from OTRecord join payemployee join employee','(cessationdate = ''1899-12-30'' or cessationdate >= [QFirstDayOfEndMonth]) and (hiredate <= [QFirstDayOfEndMonth]) and (FGetPhyYearGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndYear] and FGetPhyMonthGivenPayYrPeriod(PayGroupId,PayRecYear,PayRecPeriod) = [QEndMonth]) and (OTType != ''OTFixedRate'' and CurrentOTFreq <>0)) as temp group by employeesysid',2,1,2,1);

Commit work;