// TH Charitable Donation
update ThTaxRecord set Th_CharitableDonation = 0 where Th_CharitableDonation is null;

if exists (select 1 from sys.sysprocedure where proc_name = 'InsertNewThTaxRecord') then
  drop procedure InsertNewThTaxRecord
end if;
create procedure "DBA"."InsertNewThTaxRecord"(
in In_PersonalSysId integer,
in In_ThTaxationYear integer,
in In_ThPeriodFrom date,
in In_ThPeriodTo date,
in In_ThTaxPolicyId char(20),
in In_ThTaxEmployerId char(20),
in In_ThB_PFExceed double,
in In_ThB_GovtPension double,
in In_ThB_SchoolFund double,
in In_ThC_OldAgeAmt double,
in In_ThB_OldAgeAmtSpouse double,
in In_ThB_SeverancePay double,
in In_ThC_Taxpayer double,
in In_ThC_Spouse double,
in In_ThC_NoChildNoStudy double,
in In_ThC_NoChildStudy double,
in In_ThC_ChildNoStudyAmt double,
in In_ThC_ChildStudyAmt double,
in In_ThC_FatherAmt double,
in In_ThC_MotherAmt double,
in In_ThC_FatherSpouseAmt double,
in In_ThC_MotherSpouseAmt double,
in In_ThC_HealthInsurance double,
in In_ThC_Insurance double,
in In_ThC_ProvidentFund double,
in In_ThC_RetirementShare double,
in In_ThC_EquityFund double,
in In_ThC_Residence double,
in In_ThC_SocialSecurity double,
in In_ThA_Salary double,
in In_ThA_TotalExempted double,
in In_ThA_Expense double,
in In_ThA_TotalAllowances double,
in In_ThA_Education double,
in In_ThA_Sport double,
in In_ThA_Donation double,
in In_Th_Taxable double,
in In_Th_TaxAmt double,
in In_Th_TaxWithheld double,
in In_Th_TaxExcess double,
in In_ThB_DisabledOldAgeAmt double,
in In_ThC_DisabledSupport double,
in In_ThC_AnnuityInsurance double,
in In_ThC_NationalSavings double,
in In_ThC_FirstHomeBuyer double,
in In_ThC_FoodDomestic double,
in In_ThC_Domestic double,
in In_ThC_OTOPGoods double,
in In_ThC_YearEndDomestic double,
in In_ThC_GoodsService double,
in In_Th_CharitableDonation double,
out Out_ErrorCode integer)
begin
  if not exists(select * from ThTaxRecord where PersonalSysId = In_PersonalSysId and ThTaxationYear = In_ThTaxationYear) then
    insert into ThTaxRecord(PersonalSysId,
      ThTaxationYear,
      ThPeriodFrom,
      ThPeriodTo,
      ThTaxPolicyId,
      ThTaxEmployerId,
      ThB_PFExceed,
      ThB_GovtPension,
      ThB_SchoolFund,
      ThC_OldAgeAmt,
      ThB_OldAgeAmtSpouse,
      ThB_SeverancePay,
      ThC_Taxpayer,
      ThC_Spouse,
      ThC_NoChildNoStudy,
      ThC_NoChildStudy,
      ThC_ChildNoStudyAmt,
      ThC_ChildStudyAmt,
      ThC_FatherAmt,
      ThC_MotherAmt,
      ThC_FatherSpouseAmt,
      ThC_MotherSpouseAmt,
      ThC_HealthInsurance,
      ThC_Insurance,
      ThC_ProvidentFund,
      ThC_RetirementShare,
      ThC_EquityFund,
      ThC_Residence,
      ThC_SocialSecurity,
      ThA_Salary,
      ThA_TotalExempted,
      ThA_Expense,
      ThA_TotalAllowances,
      ThA_Education,
      ThA_Sport,
      ThA_Donation,
      Th_Taxable,
      Th_TaxAmt,
      Th_TaxWithheld,
      Th_TaxExcess,
      ThB_DisabledOldAgeAmt,
      ThC_DisabledSupport,
      ThC_AnnuityInsurance,
      ThC_NationalSavings,
      ThC_FirstHomeBuyer,
      ThC_FoodDomestic,
      ThC_Domestic,
      ThC_OTOPGoods,
      ThC_YearEndDomestic,
      ThC_GoodsService,
      Th_CharitableDonation) values(In_PersonalSysId,
      In_ThTaxationYear,
      In_ThPeriodFrom,
      In_ThPeriodTo,
      In_ThTaxPolicyId,
      In_ThTaxEmployerId,
      In_ThB_PFExceed,
      In_ThB_GovtPension,
      In_ThB_SchoolFund,
      In_ThC_OldAgeAmt,
      In_ThB_OldAgeAmtSpouse,
      In_ThB_SeverancePay,
      In_ThC_Taxpayer,
      In_ThC_Spouse,
      In_ThC_NoChildNoStudy,
      In_ThC_NoChildStudy,
      In_ThC_ChildNoStudyAmt,
      In_ThC_ChildStudyAmt,
      In_ThC_FatherAmt,
      In_ThC_MotherAmt,
      In_ThC_FatherSpouseAmt,
      In_ThC_MotherSpouseAmt,
      In_ThC_HealthInsurance,
      In_ThC_Insurance,
      In_ThC_ProvidentFund,
      In_ThC_RetirementShare,
      In_ThC_EquityFund,
      In_ThC_Residence,
      In_ThC_SocialSecurity,
      In_ThA_Salary,
      In_ThA_TotalExempted,
      In_ThA_Expense,
      In_ThA_TotalAllowances,
      In_ThA_Education,
      In_ThA_Sport,
      In_ThA_Donation,
      In_Th_Taxable,
      In_Th_TaxAmt,
      In_Th_TaxWithheld,
      In_Th_TaxExcess,
      In_ThB_DisabledOldAgeAmt,
      In_ThC_DisabledSupport,
      In_ThC_AnnuityInsurance,
      In_ThC_NationalSavings,
      In_ThC_FirstHomeBuyer,
      In_ThC_FoodDomestic,
      In_ThC_Domestic,
      In_ThC_OTOPGoods,
      In_ThC_YearEndDomestic,
      In_ThC_GoodsService,
      In_Th_CharitableDonation);
    commit work;
    if not exists(select * from ThTaxRecord where PersonalSysId = In_PersonalSysId and ThTaxationYear = In_ThTaxationYear) then
      set Out_ErrorCode=0
    else
      set Out_ErrorCode=1
    end if
  else
    set Out_ErrorCode=0
  end if
end;

if exists (select 1 from sys.sysprocedure where proc_name = 'UpdateThTaxRecord') then
  drop procedure UpdateThTaxRecord
end if;

create procedure "DBA"."UpdateThTaxRecord"(
in In_PersonalSysId integer,
in In_ThTaxationYear integer,
in In_ThPeriodFrom date,
in In_ThPeriodTo date,
in In_ThTaxPolicyId char(20),
in In_ThTaxEmployerId char(20),
in In_ThB_PFExceed double,
in In_ThB_GovtPension double,
in In_ThB_SchoolFund double,
in In_ThC_OldAgeAmt double,
in In_ThB_OldAgeAmtSpouse double,
in In_ThB_SeverancePay double,
in In_ThC_Taxpayer double,
in In_ThC_Spouse double,
in In_ThC_NoChildNoStudy double,
in In_ThC_NoChildStudy double,
in In_ThC_ChildNoStudyAmt double,
in In_ThC_ChildStudyAmt double,
in In_ThC_FatherAmt double,
in In_ThC_MotherAmt double,
in In_ThC_FatherSpouseAmt double,
in In_ThC_MotherSpouseAmt double,
in In_ThC_HealthInsurance double,
in In_ThC_Insurance double,
in In_ThC_ProvidentFund double,
in In_ThC_RetirementShare double,
in In_ThC_EquityFund double,
in In_ThC_Residence double,
in In_ThC_SocialSecurity double,
in In_ThA_Salary double,
in In_ThA_TotalExempted double,
in In_ThA_Expense double,
in In_ThA_TotalAllowances double,
in In_ThA_Education double,
in In_ThA_Sport double,
in In_ThA_Donation double,
in In_Th_Taxable double,
in In_Th_TaxAmt double,
in In_Th_TaxWithheld double,
in In_Th_TaxExcess double,
in In_ThB_DisabledOldAgeAmt double,
in In_ThC_DisabledSupport double,
in In_ThC_AnnuityInsurance double,
in In_ThC_NationalSavings double,
in In_ThC_FirstHomeBuyer double,
in In_ThC_FoodDomestic double,
in In_ThC_Domestic double,
in In_ThC_OTOPGoods double,
in In_ThC_YearEndDomestic double,
in In_ThC_GoodsService double,
in In_Th_CharitableDonation double,
out Out_ErrorCode integer)
begin
  if exists(select * from ThTaxRecord where PersonalSysId = In_PersonalSysId and ThTaxationYear = In_ThTaxationYear) then
    update ThTaxRecord set
      ThPeriodFrom = In_ThPeriodFrom,
      ThPeriodTo = In_ThPeriodTo,
      ThTaxPolicyId = In_ThTaxPolicyId,
      ThTaxEmployerId = In_ThTaxEmployerId,
      ThB_PFExceed = In_ThB_PFExceed,
      ThB_GovtPension = In_ThB_GovtPension,
      ThB_SchoolFund = In_ThB_SchoolFund,
      ThC_OldAgeAmt = In_ThC_OldAgeAmt,
      ThB_OldAgeAmtSpouse = In_ThB_OldAgeAmtSpouse,
      ThB_SeverancePay = In_ThB_SeverancePay,
      ThC_Taxpayer = In_ThC_Taxpayer,
      ThC_Spouse = In_ThC_Spouse,
      ThC_NoChildNoStudy = In_ThC_NoChildNoStudy,
      ThC_NoChildStudy = In_ThC_NoChildStudy,
      ThC_ChildNoStudyAmt = In_ThC_ChildNoStudyAmt,
      ThC_ChildStudyAmt = In_ThC_ChildStudyAmt,
      ThC_FatherAmt = In_ThC_FatherAmt,
      ThC_MotherAmt = In_ThC_MotherAmt,
      ThC_FatherSpouseAmt = In_ThC_FatherSpouseAmt,
      ThC_MotherSpouseAmt = In_ThC_MotherSpouseAmt,
      ThC_HealthInsurance = In_ThC_HealthInsurance,
      ThC_Insurance = In_ThC_Insurance,
      ThC_ProvidentFund = In_ThC_ProvidentFund,
      ThC_RetirementShare = In_ThC_RetirementShare,
      ThC_EquityFund = In_ThC_EquityFund,
      ThC_Residence = In_ThC_Residence,
      ThC_SocialSecurity = In_ThC_SocialSecurity,
      ThA_Salary = In_ThA_Salary,
      ThA_TotalExempted = In_ThA_TotalExempted,
      ThA_Expense = In_ThA_Expense,
      ThA_TotalAllowances = In_ThA_TotalAllowances,
      ThA_Education = In_ThA_Education,
      ThA_Sport = In_ThA_Sport,
      ThA_Donation = In_ThA_Donation,
      Th_Taxable = In_Th_Taxable,
      Th_TaxAmt = In_Th_TaxAmt,
      Th_TaxWithheld = In_Th_TaxWithheld,
      Th_TaxExcess = In_Th_TaxExcess,
      ThB_DisabledOldAgeAmt = In_ThB_DisabledOldAgeAmt,
      ThC_DisabledSupport = In_ThC_DisabledSupport,
      ThC_AnnuityInsurance = In_ThC_AnnuityInsurance,
      ThC_NationalSavings = In_ThC_NationalSavings,
      ThC_FirstHomeBuyer = In_ThC_FirstHomeBuyer,
      ThC_FoodDomestic = In_ThC_FoodDomestic,
      ThC_Domestic = In_ThC_Domestic,
      ThC_OTOPGoods = In_ThC_OTOPGoods,
      ThC_YearEndDomestic = In_ThC_YearEndDomestic,
      ThC_GoodsService = In_ThC_GoodsService,
      Th_CharitableDonation = In_Th_CharitableDonation where
      PersonalSysId = In_PersonalSysId and
      ThTaxationYear = In_ThTaxationYear;
    commit work;
    set Out_ErrorCode=1
  else
    set Out_ErrorCode=0
  end if
end;

commit work;